index:
   path: /home
   controller: App\Controller\controler::loadhomepage
register:
   path: /register
   controller: App\Controller\controler::loadregister

ensmainpage:
   path: /ens
   controller:  App\Controller\controler::loadensmainpage

new cours:
   path: /newcours
   controller: App\Controller\controler::loadnewcours   
stats:
   path: /statsens
   controller: App\Controller\controler::loadstatsens
etumainpage:
   path: /etu
   controller: App\Controller\controler::loadetumainpage
newcoursetu:
   path: /newcoursetu
   controller: App\Controller\controler::loadnewcoursetu   
statsetu:
   path: /statsetu
   controller: App\Controller\controler::loadstatsetu   

ajouteexe:
   path: /addexe
   controller: App\Controller\controler::addexe    


